# .github/workflows/auto-pr-dev-to-preview.yml
name: Auto PR dev → preview (with changelog)

on:
  push:
    branches: [ dev ]
  pull_request:
    types: [closed]
    branches: [ dev ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: auto-pr-dev-to-preview
  cancel-in-progress: false

jobs:
  open-pr:
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/dev')) ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       github.base_ref == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Préparer le changelog et ouvrir/mettre à jour la PR dev → preview
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = 'dev';
            const base = 'preview';

            // --- 1) Générer le changelog à partir de preview...dev (API compare)
            // Docs REST "Compare two commits"
            const compare = await github.rest.repos.compareCommits({
              owner, repo, base, head
            });

            // Regroupe par type "conventional commits"
            const groups = {
              feat: [], fix: [], perf: [], refactor: [],
              docs: [], test: [], build: [], chore: [], ci: [], other: []
            };

            const extract = (msg) => {
              //  type(scope)!: subject   | subject (#123)
              const m = msg.match(/^(\w+)(\([\w\-\.]+\))?(!)?:\s+(.+)/);
              const type = m?.[1]?.toLowerCase();
              const subject = (m?.[4] ?? msg).split('\n')[0].trim();
              return { type, subject };
            };

            const prRef = (msg) => {
              const m = msg.match(/\(#(\d+)\)/);
              return m ? ` #${m[1]}` : '';
            };

            for (const c of compare.data.commits) {
              const { type, subject } = extract(c.commit.message);
              const line = `- ${subject}${prRef(c.commit.message)}`;
              if (type && groups[type]) groups[type].push(line);
              else groups.other.push(line);
            }

            const order = ['feat','fix','perf','refactor','docs','test','build','ci','chore','other'];
            const titles = {
              feat: '✨ Features', fix: '🐞 Fixes', perf: '⚡️ Performance', refactor: '♻️ Refactor',
              docs: '📝 Docs', test: '✅ Tests', build: '🏗 Build', ci: '🤖 CI', chore: '🧹 Chore', other: '🔹 Others'
            };

            const sections = order
              .filter(k => groups[k].length)
              .map(k => `### ${titles[k]}\n${groups[k].join('\n')}`)
              .join('\n\n');

            const changelog = sections
              ? `## Changelog (dev → preview)\n\n_Comparaison_: \`${base}...${head}\`\n\n${sections}`
              : '## Changelog (dev → preview)\n\n_Aucun commit différentiel._';

            // --- 2) Vérifier s’il existe déjà une PR ouverte dev → preview
            const openPRs = await github.paginate(
              github.rest.pulls.list,
              { owner, repo, state: 'open', head: `${owner}:${head}`, base }
            );

            const title = 'chore: sync dev → preview';
            const footer = '\n\n> Changelog généré automatiquement via GitHub Actions.';

            if (openPRs.length > 0) {
              const current = openPRs[0];
              // Met à jour le body en préservant du texte éventuel, en préfixant le changelog
              const newBody = `${changelog}\n\n---\n${current.body ?? ''}${footer}`;
              await github.rest.pulls.update({
                owner, repo, pull_number: current.number, title, body: newBody
              });
              core.info(`PR mise à jour: #${current.number} (${current.html_url})`);
              return;
            }

            // --- 3) Créer la PR avec le changelog injecté
            const body = `${changelog}\n\n- Source: \`${head}\`\n- Cible: \`${base}\`\n${footer}`;
            const pr = await github.rest.pulls.create({
              owner, repo, title, head, base, body, draft: false, maintainer_can_modify: true
            });

            core.info(`PR créée: #${pr.data.number} (${pr.data.html_url})`);

            // (Optionnel) Label
            try {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: pr.data.number, labels: ['automation']
              });
            } catch (e) {
              core.warning(`Labels non ajoutés (optionnel): ${e.message}`);
            }
