name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }} 
          release-type: simple
          skip-github-pull-request: true
